campfire:
  common:
    maxBurningTimeMillis: 60000
    burningItems:
      STICK: 5000
      COAL: 15000
      OAK_PLANKS: 30000

  soul:
    maxBurningTimeMillis: 120000
    burningItems:
      STICK: 5000
      COAL: 15000
      OAK_PLANKS: 30000

  allowFireCampfireByTorch:
    torch: true
    soulTorch: true
    redstoneTorch: true

  progressBar:
    size: 10
    drawDistance: 10
    drawDistancePersonally: 3
    drawForSurvival: false
    drawYOffset: -0.20

    symbol:
      back: "&c░"
      front: "&a█"
