campfire:
  common:
    maxBurningTimeMillis: 60000
    burningItems:
      STICK: 1000
      COAL: 540
      OAK_PLANKS: 2400

  soul:
    maxBurningTimeMillis: 4200
    burningItems:
      STICK: 120
      COAL: 540
      OAK_PLANKS: 2400

  allowFireCampfireByTorch:
    torch: true
    soulTorch: true
    redstoneTorch: true

  progressBar:
    size: 10
    drawDistance: 10
    drawForSurvival: false

    symbol:
      back: "&c░"
      front: "&a█"
