name: RubyHorizonCampfires
version: '${version}'
main: team.rubyhorizon.campfires.RubyHorizonCampfires
api-version: '1.20'
load: POSTWORLD
depend: [ProtocolLib]
libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0